'use client';

type InsightsPanelProps = {
  insights: string[];
  isLoading: boolean;
};

export default function InsightsPanel({ insights, isLoading }: InsightsPanelProps) {
  if (isLoading) {
    return (
      <div className="bg-white rounded-lg border border-gray-200 p-6">
        <h2 className="text-xl font-semibold mb-4 text-gray-900">
          AI-Generated Portfolio Insights
        </h2>
        <div className="flex items-center gap-3 py-8">
          <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-blue-600"></div>
          <p className="text-sm text-gray-600">Generating insights...</p>
        </div>
      </div>
    );
  }

  if (insights.length === 0) {
    return (
      <div className="bg-white rounded-lg border border-gray-200 p-6">
        <h2 className="text-xl font-semibold mb-4 text-gray-900">
          AI-Generated Portfolio Insights
        </h2>
        <p className="text-sm text-gray-500 italic">No insights available.</p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-6">
      <div className="flex items-center gap-2 mb-4">
        <h2 className="text-xl font-semibold text-gray-900">
          AI-Generated Portfolio Insights
        </h2>
        <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800 border border-purple-200">
          AI
        </span>
      </div>
      <p className="text-sm text-gray-600 mb-4">
        Key insights and recommendations based on your portfolio data
      </p>

      <div className="space-y-3">
        {insights.map((insight, idx) => (
          <div
            key={idx}
            className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg border border-gray-200 hover:bg-gray-100 transition-colors"
          >
            <div className="flex-shrink-0 mt-0.5">
              <div className="w-6 h-6 rounded-full bg-purple-100 border border-purple-200 flex items-center justify-center">
                <span className="text-xs font-semibold text-purple-700">
                  {idx + 1}
                </span>
              </div>
            </div>
            <p className="text-sm text-gray-700 flex-1">{insight}</p>
          </div>
        ))}
      </div>

      <div className="mt-4 pt-4 border-t border-gray-200">
        <p className="text-xs text-gray-500 italic">
          These insights are generated by AI and should be reviewed by a professional.
        </p>
      </div>
    </div>
  );
}
